/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated.schedule'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated.focus'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedMaterialsIndexRouteImport } from './routes/_authenticated.materials.index'
import { Route as AuthenticatedQuizIdRouteImport } from './routes/_authenticated.quiz.$id'
import { Route as AuthenticatedFlashcardsIdRouteImport } from './routes/_authenticated.flashcards.$id'
import { Route as AuthenticatedMaterialsIdIndexRouteImport } from './routes/_authenticated.materials.$id.index'
import { Route as AuthenticatedMaterialsIdNotesRouteImport } from './routes/_authenticated.materials.$id.notes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFocusRoute = AuthenticatedFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialsIndexRoute =
  AuthenticatedMaterialsIndexRouteImport.update({
    id: '/materials/',
    path: '/materials/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizIdRoute = AuthenticatedQuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlashcardsIdRoute =
  AuthenticatedFlashcardsIdRouteImport.update({
    id: '/flashcards/$id',
    path: '/flashcards/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaterialsIdIndexRoute =
  AuthenticatedMaterialsIdIndexRouteImport.update({
    id: '/materials/$id/',
    path: '/materials/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaterialsIdNotesRoute =
  AuthenticatedMaterialsIdNotesRouteImport.update({
    id: '/materials/$id/notes',
    path: '/materials/$id/notes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/flashcards/$id': typeof AuthenticatedFlashcardsIdRoute
  '/quiz/$id': typeof AuthenticatedQuizIdRoute
  '/materials/': typeof AuthenticatedMaterialsIndexRoute
  '/materials/$id/notes': typeof AuthenticatedMaterialsIdNotesRoute
  '/materials/$id/': typeof AuthenticatedMaterialsIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/': typeof AuthenticatedIndexRoute
  '/flashcards/$id': typeof AuthenticatedFlashcardsIdRoute
  '/quiz/$id': typeof AuthenticatedQuizIdRoute
  '/materials': typeof AuthenticatedMaterialsIndexRoute
  '/materials/$id/notes': typeof AuthenticatedMaterialsIdNotesRoute
  '/materials/$id': typeof AuthenticatedMaterialsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/flashcards/$id': typeof AuthenticatedFlashcardsIdRoute
  '/_authenticated/quiz/$id': typeof AuthenticatedQuizIdRoute
  '/_authenticated/materials/': typeof AuthenticatedMaterialsIndexRoute
  '/_authenticated/materials/$id/notes': typeof AuthenticatedMaterialsIdNotesRoute
  '/_authenticated/materials/$id/': typeof AuthenticatedMaterialsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/focus'
    | '/schedule'
    | '/flashcards/$id'
    | '/quiz/$id'
    | '/materials/'
    | '/materials/$id/notes'
    | '/materials/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/analytics'
    | '/focus'
    | '/schedule'
    | '/'
    | '/flashcards/$id'
    | '/quiz/$id'
    | '/materials'
    | '/materials/$id/notes'
    | '/materials/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/focus'
    | '/_authenticated/schedule'
    | '/_authenticated/'
    | '/_authenticated/flashcards/$id'
    | '/_authenticated/quiz/$id'
    | '/_authenticated/materials/'
    | '/_authenticated/materials/$id/notes'
    | '/_authenticated/materials/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/focus': {
      id: '/_authenticated/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthenticatedFocusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials/': {
      id: '/_authenticated/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof AuthenticatedMaterialsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/$id': {
      id: '/_authenticated/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof AuthenticatedQuizIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards/$id': {
      id: '/_authenticated/flashcards/$id'
      path: '/flashcards/$id'
      fullPath: '/flashcards/$id'
      preLoaderRoute: typeof AuthenticatedFlashcardsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials/$id/': {
      id: '/_authenticated/materials/$id/'
      path: '/materials/$id'
      fullPath: '/materials/$id/'
      preLoaderRoute: typeof AuthenticatedMaterialsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials/$id/notes': {
      id: '/_authenticated/materials/$id/notes'
      path: '/materials/$id/notes'
      fullPath: '/materials/$id/notes'
      preLoaderRoute: typeof AuthenticatedMaterialsIdNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFlashcardsIdRoute: typeof AuthenticatedFlashcardsIdRoute
  AuthenticatedQuizIdRoute: typeof AuthenticatedQuizIdRoute
  AuthenticatedMaterialsIndexRoute: typeof AuthenticatedMaterialsIndexRoute
  AuthenticatedMaterialsIdNotesRoute: typeof AuthenticatedMaterialsIdNotesRoute
  AuthenticatedMaterialsIdIndexRoute: typeof AuthenticatedMaterialsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedFocusRoute: AuthenticatedFocusRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFlashcardsIdRoute: AuthenticatedFlashcardsIdRoute,
  AuthenticatedQuizIdRoute: AuthenticatedQuizIdRoute,
  AuthenticatedMaterialsIndexRoute: AuthenticatedMaterialsIndexRoute,
  AuthenticatedMaterialsIdNotesRoute: AuthenticatedMaterialsIdNotesRoute,
  AuthenticatedMaterialsIdIndexRoute: AuthenticatedMaterialsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
